language: python
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install .
- pip install pytest pytest-pep8 pytest-flakes
- pip install coveralls
script: coverage run --source=briefdruckzentrum runtests.py
after_success: coveralls
env:
  global:
  - secure: HN+9qO7DYAQM6DLrod1LZEJbd4mvqWkywBcQti96HznAu3w9RgEaeSC9134HllsByIwz9U59cgZ43lc3z0gXevm0wbst0NkPOPOG/zss1PE2cEEsvPdJ8wWP6e6/P5WSrdn5ro7dXuR1iQYo2sNNGIF5dtUTeH78hCNQKUhi/kE=
  - secure: aAEy7F8HJC3OA1nquwCqlMqzkGqIMHWgVpaxQOayK709Ha+haVmCNL+dtyQU/GrG0K26zhIf9wYQOQEngSUhLcUZsTufu6M3jfU7PqJyt4o7C/WYmD/v/ZoRB9AyFltEW7uOiFhMnxWKdQOQLjD5fTvlctR6I3q5V4E6rtGWlTE=
